// <auto-generated />
namespace CodeFirstNewDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddFavourite_OnePiece_Character : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFavourite_OnePiece_Character));
        
        string IMigrationMetadata.Id
        {
            get { return "201510151734176_AddFavourite_OnePiece_Character"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
